[server]
maxUploadSize = 500
# Disable websocket compression for mobile stability
enableWebsocketCompression = false
# Allow Streamlit Cloud to manage address/port
# address = "0.0.0.0" 

[theme]
primaryColor = "#F63049"
backgroundColor = "#111F35"
secondaryBackgroundColor = "#8A244B"
textColor = "#FFFFFF"
font = "sans serif"
