[server]
maxUploadSize = 500
enableCORS = false
enableXsrfProtection = false
address = "0.0.0.0"
enableWebsocketCompression = false

[theme]
primaryColor = "#F63049"
backgroundColor = "#111F35"
secondaryBackgroundColor = "#8A244B"
textColor = "#FFFFFF"
font = "sans serif"
